[project]
name = "chess-reasoner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chess>=1.11.1",
    "msgspec>=0.19.0",
    "wandb>=0.18.7",
    "zstandard>=0.23.0",
]
